spring.application.name=ecoscore
spring.datasource.url=jdbc:mysql://localhost:3306/ecoscore_db
spring.datasource.username=ecoscore_user
spring.datasource.password=ecoscore_pass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=8080
